name: Production Deploy on EBS

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
          aws-region: eu-central-1

      - name: Install EB CLI
        run: |
          pip install awsebcli --upgrade --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: EB Init
        run: |
          eb init Goecommerceapp \
            --platform "Docker" \
            --region eu-central-1

      - name: Set Environment variables
        run: |
          eb setenv \
            APP_ENV=prod \
            SERVER_PORT=5000 \
            APP_SECRET=${{ secrets.APP_SECRET }} \
            DB_HOST=${{ secrets.DB_HOST }} \
            DB_PORT=5432 \
            DB_NAME=${{ secrets.DB_NAME }} \
            DB_USER=${{ secrets.DB_USER }} \
            DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --environment Goecommerceapp-env

      - name: Deploy on Elastic Beanstalk
        run: |
          eb deploy Goecommerceapp-env
